### PR TITLE
Auto-load locale file

### PR DESCRIPTION
**Pull request by eukos**
This code change allows to load locale file for timeago library automatically based on application language.

### CODE REVIEW

**Comment by zinzinday** [comment]
Hi.
We can not detect yii2 language to use on timeago bcos they not match, I think we must manually configure it.
There are a few other things need to be modify, I will close this pull and refactor it
Thanks for pull

**Comment by eukos** [comment]
Hi,
ok, will wait for the plugin update

**Comment by zinzinday** [comment]
Hi, I have commit, please review, and if necessary further development

**Comment by eukos** [comment]
It looks good! Thanks for the quick response!

**Pull request closed without merging**
